// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Uid int64 `uid`
}

type ProfileResponse struct {
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	NickName string `json:"nick_name"`
	Avatar   string `json:"avatar"`
	Ctime    int64  `json:"ctime"`
}

type RegisterRequest struct {
	Phone           string `json:"phone"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type RegisterResponse struct {
}
