// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGomallUserUserIdPrefix    = "cache:gomallUser:user:id:"
	cacheGomallUserUserEmailPrefix = "cache:gomallUser:user:email:"
	cacheGomallUserUserPhonePrefix = "cache:gomallUser:user:phone:"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByEmail(ctx context.Context, email sql.NullString) (*User, error)
		FindOneByPhone(ctx context.Context, phone sql.NullString) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		sqlc.CachedConn
		table string
	}

	User struct {
		Id       int64          `db:"id"`
		Phone    sql.NullString `db:"phone"`
		Email    sql.NullString `db:"email"`
		Password string         `db:"password"`
		NickName sql.NullString `db:"nick_name"`
		Avatar   sql.NullString `db:"avatar"`
		Ctime    int64          `db:"ctime"`
		Utime    int64          `db:"utime"`
	}
)

func newUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserModel {
	return &defaultUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	gomallUserUserEmailKey := fmt.Sprintf("%s%v", cacheGomallUserUserEmailPrefix, data.Email)
	gomallUserUserIdKey := fmt.Sprintf("%s%v", cacheGomallUserUserIdPrefix, id)
	gomallUserUserPhoneKey := fmt.Sprintf("%s%v", cacheGomallUserUserPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gomallUserUserEmailKey, gomallUserUserIdKey, gomallUserUserPhoneKey)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	gomallUserUserIdKey := fmt.Sprintf("%s%v", cacheGomallUserUserIdPrefix, id)
	var resp User
	err := m.QueryRowCtx(ctx, &resp, gomallUserUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*User, error) {
	gomallUserUserEmailKey := fmt.Sprintf("%s%v", cacheGomallUserUserEmailPrefix, email)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, gomallUserUserEmailKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, email); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByPhone(ctx context.Context, phone sql.NullString) (*User, error) {
	gomallUserUserPhoneKey := fmt.Sprintf("%s%v", cacheGomallUserUserPhonePrefix, phone)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, gomallUserUserPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	gomallUserUserEmailKey := fmt.Sprintf("%s%v", cacheGomallUserUserEmailPrefix, data.Email)
	gomallUserUserIdKey := fmt.Sprintf("%s%v", cacheGomallUserUserIdPrefix, data.Id)
	gomallUserUserPhoneKey := fmt.Sprintf("%s%v", cacheGomallUserUserPhonePrefix, data.Phone)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Phone, data.Email, data.Password, data.NickName, data.Avatar, data.Ctime, data.Utime)
	}, gomallUserUserEmailKey, gomallUserUserIdKey, gomallUserUserPhoneKey)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	gomallUserUserEmailKey := fmt.Sprintf("%s%v", cacheGomallUserUserEmailPrefix, data.Email)
	gomallUserUserIdKey := fmt.Sprintf("%s%v", cacheGomallUserUserIdPrefix, data.Id)
	gomallUserUserPhoneKey := fmt.Sprintf("%s%v", cacheGomallUserUserPhonePrefix, data.Phone)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Phone, newData.Email, newData.Password, newData.NickName, newData.Avatar, newData.Ctime, newData.Utime, newData.Id)
	}, gomallUserUserEmailKey, gomallUserUserIdKey, gomallUserUserPhoneKey)
	return err
}

func (m *defaultUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGomallUserUserIdPrefix, primary)
}

func (m *defaultUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
